;CONFIGURACIONES INICIALES
__CONFIG _XT_OSC & _WDT_OFF & _PWRTE_ON & _CP_OFF

LIST P = 16F628A	    ;INDICAMOS EL PROCESADOR A USAR

INCLUDE <P16F628A.INC>      ;AGREGAMOS LA LIBRERÍA A USAR
    

ORG	0x00		    ;INICIO DEL PROGRAMA

    ;NOS MOVEMOS A BANCO 1 PARA CONFIGURAR LOS PUERTOS
    
    BSF	    STATUS,5
    
    BSF	    TRISB,7	    ;PUERTO RB7 COMO ENTRADA
    BCF	    TRISA,0	    ;PUERTO RA0 COMO SALIDA
    
    BCF	    STATUS,5	    ;REGRESAMOS AL BANCO 0
    
    
    ;TERMINAMOS DE CONFIGURAR LOS PUERTOS
    
    INICIO:
	
	BTFSC	PORTB,7	    ;IF RB7 ==1
	BCF	PORTA,0	    ;APAGAMOS EL LED DE RA0
	BTFSS   PORTB,7
	BSF	PORTA,0	    ;(ELSE) PRENDEMOS RA0
	GOTO	INICIO	    ;REGRESO 3 LINEAS DE CÓDIGO.
			    ;TAMBIEN PODEMOS USAR GOTO	INICIO PARA REGRESAR

END			    ;FIN DEL PROGRAMA